image: 
  name: schemacrawler/schemacrawler:v16.16.3
  entrypoint: [""]

variables:
  USER: "get_username_from_secrets"
  PASSWORD: "get_password_from_secrets"

schema-lint:
  script:
    - shopt -s expand_aliases
    - source ~/.bashrc
    - schemacrawler --server=postgresql --database=compliance-platform-dev --host=${{ secrets.HOST }} --user:${{ secrets.USER }} --password:${{ secrets.PASSWORD }} --info-level=standard --command=lint --output-file lint-report.txt --log-level=CONFIG
    - schemacrawler --server=postgresql --database=compliance-platform-dev --host=${{ secrets.HOST }} --user:${{ secrets.USER }} --password:${{ secrets.PASSWORD }} --info-level=standard --command=script --tables "Authors|Books|BookAuthors" --script-language python --script mermaid.py --output-file mermaid-er.txt --log-level=CONFIG
  artifacts:
    paths:
      - lint-report.txt
      - mermaid-er.txt
