name: SchemaCrawler Job to Lint Database Schema

on: [push]

jobs:
  schemacrawler-job:
    runs-on: ubuntu-latest

    name: SchemaCrawler Job to Lint Database Schema
    steps:

      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v2

      - id: remove-old
        name: Remove previous lint report created by the SchemaCrawler Action
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase true
          git rm lint-report.txt
          git commit -m "Remove old schema lint report"
          git pull
          git push

      - id: schemacrawler
        name: Run SchemaCrawler Action with specified command-line
        uses: schemacrawler/SchemaCrawler-Action@v16.11.5
        with:
          entrypoint: /schemacrawler.sh
          args: --server=sqlite --database=schemacrawler.sqlite --user:env USER --password:env PASSWORD --info-level=standard --command=lint --linter-configs /schemacrawler-linter-configs.xml --lint-dispatch=terminate_system --output-file lint-report.txt --log-level=FINE
        env:
          USER: user-possibly-from-secrets
          PASSWORD: password-possibly-from-secrets

      - id: checkin
        name: Checkin lint report created by the SchemaCrawler Action
        run: |
          sleep $((20 + RANDOM % 20)) # avoid clashes with other actions
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase true
          git add lint-report.txt
          git commit -m "Schema lint report generated by SchemaCrawler Action for GitHub Actions"
          git pull
          git push

      - id: check-success
        name: Fail the entire job if SchemaCrawler lint report has failures
        run: |
          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] && echo "SchemaCrawler lint check succeeded" || echo "SchemaCrawler lint check shows failures - see the lint report"
          [ ${{ steps.schemacrawler.outputs.exit_status }} -eq 0 ] || exit 1

